name: Build
on:
  release:
    tags:
      - v*

jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:

      - name: Login to Registry
        if: github.event.action == 'published' # temporary workaround
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | \
          docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Check out code into the Go module directory
        if: github.event.action == 'published' # temporary workaround
        uses: actions/checkout@v1

      - name: Build image
        if: github.event.action == 'published'
        run: |
          export IMAGE_TAG=$(echo ${GITHUB_REF} | sed -e "s/refs\/tags\///g")
          export IMAGE_TAG_MINOR=$(echo ${IMAGE_TAG} | awk '{match($0,"v[0-9]\.[0-9]",a)}END{print a[0]}')
          export IMAGE_TAG_MAJOR=$(echo ${IMAGE_TAG} | awk '{match($0,"v[0-9]",a)}END{print a[0]}')
          docker build \
          -t matoous/golangci-lint-action \
          -t matoous/golangci-lint-action:${IMAGE_TAG} \
          -t matoous/golangci-lint-action:${IMAGE_TAG_MINOR} \
          -t matoous/golangci-lint-action:${IMAGE_TAG_MAJOR} .

      - name: Publish image
        if: github.event.action == 'published' # temporary workaround
        run: docker push matoous/golangci-lint-action

      - name: Logout
        if: github.event.action == 'published' # temporary workaround
        run: docker logout
